import { mkdirSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { assertWriteable, createExclusiveFile, replaceFileAtomic, statOptional } from "../shared/fs"
import { secureCanonicalPath } from "../shared/secure-path"
import { withExclusiveFileLockSync } from "../shared/file-lock"

export const BUILTIN_SKILL_IDS = ["forge-workflow", "ci-workflow", "runner-workflow"] as const
export const BUILTIN_SKILL_MARKER = "<!-- Generated by agent-gvozd: builtin skill -->"

export interface SkillPlan {
  created: string[]
  updated: string[]
  unchanged: string[]
  writes: Array<{ target: string; content: string; previous?: string }>
}

export function validateBuiltinSkill(id: string, content: string): void {
  const frontmatter = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(content)?.[1]
  const name = frontmatter?.match(/^name: (.+)$/m)?.[1]
  const description = frontmatter?.match(/^description: (.+)$/m)?.[1]
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(id) || id.length > 64 || name !== id
    || !description || description.length > 1024 || !content.includes(`\n${BUILTIN_SKILL_MARKER}\n`)) {
    throw new Error(`Invalid packaged skill: ${id}`)
  }
}

function safeDirectory(path: string): void {
  secureCanonicalPath(path, "Managed skills directory")
  const stat = statOptional(path)
  if (stat && !stat.isDirectory()) throw new Error(`Unsafe managed skills directory: ${path}`)
  assertWriteable(path, "Managed skills directory")
}

/** Pure preflight: even an identical unmanaged skill is never adopted. */
export function planBuiltinSkills(packageRoot: string, destination: string): SkillPlan {
  safeDirectory(destination)
  const plan: SkillPlan = { created: [], updated: [], unchanged: [], writes: [] }
  for (const id of BUILTIN_SKILL_IDS) {
    const source = secureCanonicalPath(join(packageRoot, "defaults", "skills", id, "SKILL.md"), "Packaged skill")
    const sourceStat = statOptional(source)
    if (!sourceStat?.isFile()) throw new Error(`Missing packaged skill: ${id}`)
    const content = readFileSync(source, "utf8")
    validateBuiltinSkill(id, content)
    // V2 also discovers flat Markdown files: do not silently shadow one.
    const flat = secureCanonicalPath(join(destination, `${id}.md`), "Skill alias")
    if (statOptional(flat)) throw new Error(`Unmanaged skill conflict: ${flat}`)
    safeDirectory(join(destination, id))
    const target = secureCanonicalPath(join(destination, id, "SKILL.md"), "Managed skill")
    const stat = statOptional(target)
    if (!stat) {
      plan.created.push(target)
      plan.writes.push({ target, content })
      continue
    }
    if (!stat.isFile()) throw new Error(`Unsafe managed skill: ${target}`)
    assertWriteable(target, "Managed skill")
    const previous = readFileSync(target, "utf8")
    if (!previous.includes(`\n${BUILTIN_SKILL_MARKER}\n`)) throw new Error(`Unmanaged skill conflict: ${target}`)
    if (previous === content) plan.unchanged.push(target)
    else {
      plan.updated.push(target)
      plan.writes.push({ target, content, previous })
    }
  }
  return plan
}

/** Callers may hold their setup/sync lock; this additional lock serializes skill writers. */
export function installBuiltinSkills(packageRoot: string, destination: string, options: { check?: boolean; expected?: SkillPlan } = {}): SkillPlan {
  const preview = planBuiltinSkills(packageRoot, destination)
  if (options.check) return preview
  const lockRoot = secureCanonicalPath(dirname(destination), "Skills lock root")
  safeDirectory(lockRoot)
  mkdirSync(lockRoot, { recursive: true, mode: 0o700 })
  return withExclusiveFileLockSync(join(lockRoot, ".agent-gvozd-skills.lock"), () => {
    const plan = planBuiltinSkills(packageRoot, destination)
    if (JSON.stringify(plan) !== JSON.stringify(options.expected ?? preview)) {
      throw new Error("Managed skills changed since preview; review and rerun")
    }
    for (const write of plan.writes) {
      safeDirectory(dirname(write.target))
      mkdirSync(dirname(write.target), { recursive: true, mode: 0o700 })
      safeDirectory(dirname(write.target))
      secureCanonicalPath(write.target, "Managed skill")
      if (write.previous === undefined) createExclusiveFile(write.target, write.content)
      else {
        const stat = statOptional(write.target)
        if (!stat?.isFile() || readFileSync(write.target, "utf8") !== write.previous) {
          throw new Error(`Concurrently changed managed skill: ${write.target}`)
        }
        replaceFileAtomic(write.target, write.content)
      }
    }
    return plan
  }, "skills installation")
}
