import { afterEach, describe, expect, test } from "bun:test"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, unlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { loadConfig } from "./config"
import { syncAgents } from "./sync"
import { withExclusiveFileLock } from "../shared/file-lock"

const roots: string[] = []

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function fixture() {
  const root = realpathSync(mkdtempSync(join(tmpdir(), "gvozd-sync-")))
  roots.push(root)
  mkdirSync(join(root, ".git"))
  return { root, config: loadConfig(root, { configRoot: join(root, "global") }) }
}

describe("legacy project sync templates", () => {
  test("check reports missing required config and schema without writing", () => {
    const { root, config } = fixture()
    const result = syncAgents(config, { check: true })
    expect(result.created).toContain(join(root, "docs", ".gvozd", "config.jsonc"))
    expect(result.created).toContain(join(root, "docs", ".gvozd", "schema.json"))
    expect(existsSync(join(root, "docs"))).toBe(false)
    expect(existsSync(join(root, ".agent-gvozd-sync.lock"))).toBe(false)
  })

  test("check detects managed schema drift and missing schema without changing files", () => {
    const { root, config } = fixture()
    syncAgents(config)
    const schemaPath = join(root, "docs", ".gvozd", "schema.json")
    const stale = `${readFileSync(schemaPath, "utf8")} \n`
    writeFileSync(schemaPath, stale)
    expect(syncAgents(config, { check: true }).updated).toContain(schemaPath)
    expect(readFileSync(schemaPath, "utf8")).toBe(stale)

    unlinkSync(schemaPath)
    expect(syncAgents(config, { check: true }).created).toContain(schemaPath)
    expect(existsSync(schemaPath)).toBe(false)
  })

  test("preserves user config and recognizes the exact unmarked legacy schema", () => {
    const { root, config } = fixture()
    syncAgents(config)
    const directory = join(root, "docs", ".gvozd")
    const configPath = join(directory, "config.jsonc")
    const userConfig = '{\n  // user owned\n  "agents": {}\n}\n'
    writeFileSync(configPath, userConfig)
    const schemaSource = readFileSync(join(process.cwd(), "defaults", "schema.json"), "utf8")
    const legacy = JSON.parse(schemaSource)
    delete legacy.$comment
    delete legacy["x-agent-gvozd-schema-version"]
    const schemaPath = join(directory, "schema.json")
    const legacySource = `${JSON.stringify(legacy, null, 2)}\n`
    writeFileSync(schemaPath, legacySource)

    expect(syncAgents(config, { check: true }).updated).toContain(schemaPath)
    expect(readFileSync(schemaPath, "utf8")).toBe(legacySource)
    syncAgents(config)
    expect(readFileSync(configPath, "utf8")).toBe(userConfig)
    expect(readFileSync(schemaPath, "utf8")).toContain("Generated by agent-gvozd sync")
    expect(existsSync(join(root, ".agent-gvozd-sync.lock"))).toBe(false)
  })

  test("an active project sync lock blocks mutation before files change", async () => {
    const { root, config } = fixture()
    const lock = join(root, ".agent-gvozd-sync.lock")
    let release!: () => void
    const waiting = new Promise<void>((resolve) => { release = resolve })
    const owner = withExclusiveFileLock(lock, async () => waiting)
    await Promise.resolve()
    expect(() => syncAgents(config)).toThrow("Another Gvozd sync")
    expect(existsSync(join(root, "docs"))).toBe(false)
    expect(existsSync(join(root, ".opencode"))).toBe(false)
    release()
    await owner
    expect(existsSync(lock)).toBe(false)
  })

  test("a failed mutation removes only its owned sync lock", () => {
    const { root, config } = fixture()
    const agents = join(root, ".opencode", "agents")
    mkdirSync(agents, { recursive: true })
    writeFileSync(join(agents, "master.md"), "user owned\n")
    expect(() => syncAgents(config)).toThrow("non-generated")
    expect(existsSync(join(root, ".agent-gvozd-sync.lock"))).toBe(false)
    expect(readFileSync(join(agents, "master.md"), "utf8")).toBe("user owned\n")
  })
})
