import { parse, type ParseError } from "jsonc-parser/lib/esm/main.js"
import { CONFIG_SCHEMA_VERSION } from "./release-metadata"

export const GENERATED_MARKER = "# Generated by agent-gvozd sync. Do not edit this file directly."
export const GENERATED_PLUGIN_MARKER = "// Generated by agent-gvozd sync. Do not edit this file directly."

export function hasGeneratedAgentMarker(content: string): boolean {
  return content.startsWith(`---\n${GENERATED_MARKER}\n`)
}

export function hasGeneratedPluginMarker(content: string): boolean {
  return content.startsWith(`${GENERATED_PLUGIN_MARKER}\n`)
}

export function hasGeneratedSchemaMarker(content: string): boolean {
  const errors: ParseError[] = []
  const value = parse(content, errors, { allowTrailingComma: true, disallowComments: false })
  if (errors.length > 0 || value === null || typeof value !== "object" || Array.isArray(value)) {
    return false
  }
  if (value.$comment !== GENERATED_PLUGIN_MARKER) return false
  const version = value["x-agent-gvozd-schema-version"]
  // Files written by an older managed schema version remain owned by sync and
  // are upgraded in place; unknown newer versions stay unmanaged.
  return typeof version === "number"
    && Number.isSafeInteger(version)
    && version >= 1
    && version <= CONFIG_SCHEMA_VERSION
}

function stable(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stable)
  if (!value || typeof value !== "object") return value
  return Object.fromEntries(Object.entries(value as Record<string, unknown>)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, entry]) => [key, stable(entry)]))
}

export function isEquivalentLegacySchema(content: string, generated: string): boolean {
  try {
    const previous = JSON.parse(content) as Record<string, unknown>
    const expected = JSON.parse(generated) as Record<string, unknown>
    if (!previous || Array.isArray(previous) || previous.$comment !== undefined) return false
    if (previous["x-agent-gvozd-schema-version"] !== undefined
      && previous["x-agent-gvozd-schema-version"] !== CONFIG_SCHEMA_VERSION) return false
    delete previous.$comment
    delete previous["x-agent-gvozd-schema-version"]
    delete expected.$comment
    delete expected["x-agent-gvozd-schema-version"]
    return JSON.stringify(stable(previous)) === JSON.stringify(stable(expected))
  } catch {
    return false
  }
}
