export const GENERATED_MARKER = "# Generated by agent-gvozd sync. Do not edit this file directly."
export const GENERATED_PLUGIN_MARKER = "// Generated by agent-gvozd sync. Do not edit this file directly."
